export const PROGRAM_ID = "9XXmc9PaoKTqSGW1YgxTCPzmQRFDRBxnGGjXnwZWCK8m";

export const TOKEN_ID = "6D3XiqeC1DU5Sxug6HU7MAv6Cs8sV167VsE72YSWBb1E";
export const AMOUNT = 5;

export const SPL_ASSOCIATED_TOKEN_ACCOUNT_PROGRAM_ID =
  "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL";
